name: make dist

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make-dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build dist
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add make git zip
          git config --global --add safe.directory '*'
          make dist
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/photobook*.zip
        
    - name: Artifacts (build)
      uses: actions/upload-artifact@v3
      with:
        name: build artifacts
        path: photobook.pdf

    - name: Artifacts (dist)
      uses: actions/upload-artifact@v3
      with:
        name: dist artifacts
        path: dist/photobook*.zip
        
    - name: Upload to CTAN
      uses: paolobrasolin/ctan-submit-action@v1
      with: 
        action: upload
        file_path: dist/photobook*.zip
        fields: |
            pkg: photobook
            version: 0.0.1
            author: Alex A. Naanou
            email: alex.nanou@gmail.com
            uploader: alex.nanou@gmail.com 
            license: BSD (3-Clause)
            summary: Document class for making photo books.
        
        
