name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build dist
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add |
            make 
            git 
            zip
          git config --global --add safe.directory '*'
          make dist
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/photobook*.zip
        
    - name: Artifacts (build)
      uses: actions/upload-artifact@v3
      with:
        name: build artifacts
        path: photobook.pdf

    - name: Artifacts (dist)
      uses: actions/upload-artifact@v3
      with:
        name: dist artifacts
        path: dist/photobook*.zip
        
        
