name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: xu-cheng/texlive-action/full@v1
      
    - name: Make manual
      run: make -n dist
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        if: startsWith(github.ref, 'refs/tags/')
        files: dist/photobook*.zip
        
        
